image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
  branches:
    master:
      - step:
          name: create tar file
          script:
            - tar -zcvf deploy.tar.gz .
          artifacts:
            - deploy.tar.gz
          after-script:
            - ls
            - echo "deploy zip created successfully"
      - step: 
          name: Deploy to prod app
          script: 
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $MASTER_APP_NAME
                ZIP_FILE: 'deploy.tar.gz'
                WAIT: 'true'
          after-script:
            - echo "Build successful"